# Generated by Django 2.0.5 on 2018-08-18 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinysite', '0002_auto_20180817_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='栏目分类')),
            ],
            options={
                'verbose_name': '栏目分类',
                'verbose_name_plural': '栏目分类',
            },
        ),
        migrations.AddField(
            model_name='column',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tinysite.Category', verbose_name='所属分类'),
        ),
    ]
