# Generated by Django 2.0.5 on 2018-09-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinysite', '0002_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='category', max_length=256, verbose_name='类别网址'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
