# Generated by Django 2.0.5 on 2018-08-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinysite', '0003_auto_20180818_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='home_display',
        ),
        migrations.AlterField(
            model_name='column',
            name='nav_display',
            field=models.BooleanField(default=True, verbose_name='导航显示'),
        ),
    ]
